baseURL = 'http://ivesliu1026.github.io/'
languageCode = ['en-us']
languageName = ['English']
title = "Ives Liu's nook"
theme = 'LoveIt'

[author]
    name = 'Ives Liu'
    email = 'mailto:zhiy0517xiang@gmail.com'

[params.header.title]
    name = "Ives Liu's nook"    
    
[params.home.profile]
    title = "Hello, I'm Ives Liu!"
    avatarURL = 'img/Ives.jpg'
    subtitle = 'An undergrauate student at NYCU studying Electrical and Computer Engineering'
        



[params.social.github]
    weight = 1
    name = 'Github'
    url = 'https://github.com/IvesLiu1026'
[params.social.instagram]
    weight = 2
    name = 'Instagram'
    url = 'https://www.instagram.com/iveees._/?theme=dark'
[params.social.email]
    weight = 3
    name = 'Email'
    url = 'mailto:zhiy0517xiang@gmail.com'
[params.social.facebook]
    weight = 4    
    name = 'Facebook'
    url = 'https://www.facebook.com/profile.php?id=100008267281647'
[params.social.discord]
    weight = 5
    name = 'Discord'
    url = 'https://discord.gg/cr5qVq3g'
[params.social.twitter]
    weight = 6
    name = 'Twitter'
    url = 'https://twitter.com/Iveees_'
[params.social.linkedin]
    weight = 7
    name = 'LinkedIn'
    url = 'https://www.linkedin.com/in/liu-ives-92612a245/'


[params.Search]
    enable = true
        # type of search engine ("lunr", "algolia")
        type = "algolia"
        # max index length of the chunked content
        contentLength = 4000
        # placeholder of the search bar
        placeholder = ""
        # max number of results length
        maxResultLength = 10
        # snippet length of the result
        snippetLength = 30
        # HTML tag name of the highlight part in results
        highlightTag = "em"
        # whether to use the absolute URL based on the baseURL in search index
        absoluteURL = false
[params.Search.algolia]
    appId = "YOUR_ALGOLIA_APP_ID"
    apiKey = "YOUR_ALGOLIA_API_KEY"
    indexName = "YOUR_ALGOLIA_INDEX_NAME"



[menu]
    [[menu.main]]
        weight = 1
        identifier = "about"
        pre = ""
        post = "<i class='fa fa-person-walking'></i>"
        name = "About"
        url = "/about/"
    [[menu.main]]
        weight = 2
        identifier = "archives"
        # you can add extra information before the name (HTML format is supported), such as icons
        pre = ""
        # you can add extra information after the name (HTML format is supported), such as icons
        post = "<i class='fa fa-archive'></i>"
        name = "Archives"
        url = "/posts/"
        # title will be shown when you hover on this menu link
        title = ""
    [[menu.main]]
        weight = 3
        identifier = "tags"
        pre = ""
        post = "<i class='fa fa-tags'></i>"
        name = "Tags"
        url = "/tags/"
        title = ""
    [[menu.main]]
        weight = 4
        identifier = "categories"
        pre = ""
        post = "<i class='fa fa-folder'></i>"
        name = "Categories"
        url = "/categories/"
        title = ""
    [[menu.main]]
        weight = 5
        identifier = "github"
        pre = "<i class='fab fa-github'></i>"
        post = ""
        url = "https://github.com/IvesLiu1026"
        title = ""