baseURL = 'http://ivesliu1026.github.io/'
languageCode = ['en-us']
languageName = ['English']
title = "Ives Liu's nook"
theme = 'LoveIt'

[author]
    name = 'Ives Liu'
    email = 'mailto:zhiy0517xiang@gmail.com'

[params.header.title]
    name = "Ives Liu's nook"    
    
[params.home.profile]
    title = "Hello, I'm Ives Liu!"
    avatarURL = 'img/Ives.jpg'
    subtitle = 'An undergrauate student at NYCU studying Electrical and Computer Engineering'
        


[params.social]
    github = 'https://github.com/IvesLiu1026'
    instagram = 'https://www.instagram.com/iveees._/?theme=dark'
    facebook = 'https://www.facebook.com/profile.php?id=100008267281647'
    discord = 'https://discord.gg/cr5qVq3g'
    twitter = 'https://twitter.com/Iveees_'
    email = 'mailto:zhiy0517xiang@gmail.com'
    linkedin = 'https://www.linkedin.com/in/liu-ives-92612a245/'



[params.Search]
    enable = true
        # type of search engine ("lunr", "algolia")
        type = "algolia"
        # max index length of the chunked content
        contentLength = 4000
        # placeholder of the search bar
        placeholder = ""
        # max number of results length
        maxResultLength = 10
        # snippet length of the result
        snippetLength = 30
        # HTML tag name of the highlight part in results
        highlightTag = "em"
        # whether to use the absolute URL based on the baseURL in search index
        absoluteURL = false
[params.Search.algolia]
    appId = "YOUR_ALGOLIA_APP_ID"
    apiKey = "YOUR_ALGOLIA_API_KEY"
    indexName = "YOUR_ALGOLIA_INDEX_NAME"



[menu]
    [[menu.main]]
        weight = 1
        identifier = "about"
        pre = ""
        post = "<i class='fa fa-person-walking'></i>"
        name = "About_"
        url = "/about/"
    [[menu.main]]
        weight = 2
        identifier = "archives"
        # you can add extra information before the name (HTML format is supported), such as icons
        pre = ""
        # you can add extra information after the name (HTML format is supported), such as icons
        post = "<i class='fa fa-archive'></i>"
        name = "Archives_"
        url = "/posts/"
        # title will be shown when you hover on this menu link
        title = ""
    [[menu.main]]
        weight = 3
        identifier = "tags"
        pre = ""
        post = "<i class='fa fa-tags'></i>"
        name = "Tags_"
        url = "/tags/"
        title = ""
    [[menu.main]]
        weight = 4
        identifier = "categories"
        pre = ""
        post = "<i class='fa fa-folder'></i>"
        name = "Categories_"
        url = "/categories/"
        title = ""